FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY . .

#ruleaza shell-ul pt a pastra containerul activ 
#CMD tail -f /dev/null


#ENTRYPOINT java -jar NotesToDoList.jar
# NU ASTEAPTA CA BD SA PORNEASCA. SE TOT INCEARCA CONEXIUNEA SI DA GRES PT CA BAZA DE DATE NU E GATA. DE ASTA ANULE COMANDA. SI PORNESC JARU MANUAL DIN CONTAINER


#docker build -t backend-notestodo .
#docker run -it -p 8000:8000 backend-notestodo sh